### ISSUE TITLE
+obbo unknown command [see pull request #1]

### ISSUE THREAD

**Issue by daniel-heatwave** [phoenixprojectsoftware/shootertourneys#2]
The `object.cfg` file doesn't work. It shows this in console;
`unknown command: +obbo`
`unknown command: -obbo`
Also it isn't in the Keyboard options in version 1.1

# Moderator edit
See #1

**Comment by barney-heatwave** [comment]
We are aware of this. You didn't have to open this issue. You could've added more commits to your branch and updated your pull request.
